version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bleach
    versions:
    - 3.1.1
  - dependency-name: jinja2
    versions:
    - 2.10.1
