# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 18:45
from __future__ import unicode_literals

import uuid

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [('authorization', '0005_fk_uuid')]

    operations = [
        # add dummy field again, otherwise AlterUniqueTogether fails
        migrations.AddField(
            model_name='authorization',
            name='applicationold',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='authorization',
            unique_together=set([('user', 'application')]),
        ),
        # delete dummy field again
        migrations.RemoveField(
            model_name='authorization', name='applicationold'
        ),
    ]
