# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     primary_key=True,
                     serialize=False,
                     to='users.CustomUser')
                 ),
                ('verification_token',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     unique=True)
                 ),
                ('is_verified',
                 models.BooleanField(
                     default=False)
                 ),
            ],
        ),
    ]
