# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('registration', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='email_verification',
                serialize=False,
                to='users.CustomUser',
            ),
        )
    ]
