# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_uuid'),
        ('authorization', '0004_fk_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='application',
            old_name='uuid',
            new_name='id',
        )
    ]
